apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: amazon-cloudwatch
  labels:
    app: cloudwatch-agent
data:
  agent.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "my-cluster-1",
            "metrics_collection_interval": 60,
            "force_flush_interval": 5
          }
        }
      }
    }

